# Generated by Django 5.2.10 on 2026-01-13 21:17

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_token',
            field=models.CharField(db_index=True, default=bookings.models.generate_booking_token, max_length=64),
        ),
    ]
