# Generated by Django 5.2.10 on 2026-01-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_booking_token'),
        ('vehicles', '0002_remove_vehicle_vehicles_ve_brand_768e26_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_token', '-created_at'], name='booking_token_created_idx'),
        ),
    ]
