# Generated by Django 5.2.10 on 2026-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(db_index=True)),
                ('fuel_type', models.CharField(db_index=True, max_length=20)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['brand'], name='vehicles_ve_brand_768e26_idx'), models.Index(fields=['fuel_type'], name='vehicles_ve_fuel_ty_37bc20_idx'), models.Index(fields=['price'], name='vehicles_ve_price_da359f_idx')],
            },
        ),
    ]
