# Generated by Django 5.2.10 on 2026-01-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_brand_768e26_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_fuel_ty_37bc20_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_price_da359f_idx',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'fuel_type'], name='vehicle_brand_fuel_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price', '-created_at'], name='vehicle_price_created_idx'),
        ),
    ]
