# Generated by Django 5.2.10 on 2026-01-13 21:17

import bookmarks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_bookmark_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_token',
            field=models.CharField(db_index=True, default=bookmarks.models.generate_bookmark_token, max_length=64),
        ),
    ]
