# Generated by Django 5.2.10 on 2026-01-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmark_bookmark_token'),
        ('vehicles', '0002_remove_vehicle_vehicles_ve_brand_768e26_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['bookmark_token', '-created_at'], name='bookmark_token_created_idx'),
        ),
    ]
